[env]
TERM="alacritty"

[colors]
transparent_background_colors = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "ExtraLight"

[window]
padding = { x = 10, y = 10 }
# opacity = 0.80
# opacity = 0.94
blur = true
dimensions = { columns = 140, lines = 50 }
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars= "\u001BF" },
  { key = "Left",  mods= "Alt", chars= "\u001BB" },
  { key = "Space", mods = "Control|Shift", action = "None" },
  { key = "Up",    mods = "Control|Shift", chars = "\u001B[1;6A" },
  { key = "Down",  mods = "Control|Shift", chars = "\u001B[1;6B" },
  { key = "Right", mods = "Control|Shift", chars = "\u001B[1;6C" },
  { key = "Left",  mods = "Control|Shift", chars = "\u001B[1;6D" },
  # { key = "H", mods = "Control|Alt", chars = "\u001B[1;6D" },  # Left 
  # { key = "L", mods = "Control|Alt", chars = "\u001B[1;6C" }  # Right
]

