[General]
frontend=widgetsboxmodel
hotkey=F3
last_report=1693386255
showTray=true
telemetry=true
terminal=Gnome Terminal

[applications_xdg]
enabled=true

[calculator_muparser]
enabled=true

[clipboard]
enabled=false

[files]
enabled=false
paths=@Invalid()

[qmlboxmodel]
windowPosition=@Point(609 196)

[terminal]
enabled=true

[widgetsboxmodel]
alwaysOnTop=true
clearOnHide=false
clientShadow=true
displayScrollbar=false
followCursor=true
hideOnFocusLoss=true
historySearch=true
itemCount=5
quitOnClose=false
showCentered=true
showFallbacksOnEmpty=true
systemShadow=true
theme=Spotlight
windowPosition=@Point(607 196)
