return {
  -- "zbirenbaum/copilot.lua",
  -- cmd = "Copilot",
  -- build = ":Copilot auth",
  -- opts = {
  --   -- suggestion = { enabled = false },
  --   -- panel = { enabled = false },
  --   -- filetypes = {
  --   --   markdown = true,
  --   --   help = true,
  --   -- },
  -- },
  -- keys = {
  --   vim.keymap.set(
  --     "n",
  --     "<leader>at",
  --     ":Copilot enable<CR>:echo 'Copilot enabled'<CR>",
  --     { noremap = true, silent = true, desc = "Enable copilot suggestions" }
  --   ),
  --
  --   vim.keymap.set(
  --     "n",
  --     "<leader>ar",
  --     ":Copilot disable<CR>:echo 'Copilot disabled'<CR>",
  --     { noremap = true, silent = true, desc = "Disable copilot suggestions" }
  --   ),
  -- },
}
