"$schema" = 'https://starship.rs/config-schema.json'


format = """
[](color_orange)\
$os\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$custom\
$docker_context\
$conda\
[](fg:color_bg3)\
[ ](fg:color_bg1)\
$line_break$character"""

right_format = """$time"""

# Define colors - vague.nvim inspired
palette = 'monokai'

command_timeout = 200

[fill]
symbol = " "

# [palettes.vague]
# color_fg0 = '#cdcdcd'
# color_bg1 = '#1c1c24'
# color_bg3 = '#252530'
# color_blue = '#6e94b2'
# color_aqua = '#9bb4bc'
# color_green = '#7fa563'
# color_orange = '#e0a363'
# color_purple = '#bb9dbd'
# color_red = '#d8647e'
# color_yellow = '#f3be7c'

[palettes.monokai]
color_fg0 = '#f8f8f2'
color_bg1 = '#272822'
color_bg3 = '#3e3d32'
color_blue = '#66d9ef'
color_aqua = '#a1efe4'
color_green = '#a6e22e'
color_orange = '#fd971f'
color_purple = '#ae81ff'
color_red = '#f92672'
color_yellow = '#e6db74'

[aws]
symbol = "  "

[buf]
symbol = " "

[bun]
symbol = " "

[c]
symbol = " "



[cmake]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[deno]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
symbol = "  "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
disabled = true

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "



[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[kubernetes]
disabled = true

[custom.k8s]
command = 'kubectl config current-context | sed -E "s#.*/##"'
format = '[[ 󱃾 $output( $namespace) ](fg:color_fg0 bg:color_bg3)]($style)'
when = 'kubectl config current-context > /dev/null 2>&1'
style = "bold blue"
shell = "sh"

[time]
disabled = false
time_format = "%T"
format = '[$time]($style)'
style = "fg:color_fg0"
